/**
 * Canonical error code catalog per Tahap 3.E §2.3.
 *
 * F1 covers AUTH_*, FORBIDDEN_*, VALIDATION_*, NOT_FOUND, CONFLICT,
 * DUPLICATE_TELEPON, BUSINESS_LAST_SUPER_ADMIN, BUSINESS_CANNOT_DEACTIVATE_SELF,
 * RATE_LIMITED, INTERNAL_ERROR.
 *
 * Subsequent fases append more codes (DUPLICATE_PESERTA, BUSINESS_HEWAN_*, etc.).
 * Keep additions ALPHABETIZED within their group.
 */

export const ErrorCodes = {
  // Authentication
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_LOCKED: 'AUTH_LOCKED',
  AUTH_INACTIVE: 'AUTH_INACTIVE',

  // Authorization
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_REQUIRED: 'VALIDATION_REQUIRED',
  VALIDATION_FORMAT: 'VALIDATION_FORMAT',
  VALIDATION_PIN_POLICY: 'VALIDATION_PIN_POLICY',

  // Resource state
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  DUPLICATE_TELEPON: 'DUPLICATE_TELEPON',

  // Business rules
  BUSINESS_LAST_SUPER_ADMIN: 'BUSINESS_LAST_SUPER_ADMIN',
  BUSINESS_CANNOT_DEACTIVATE_SELF: 'BUSINESS_CANNOT_DEACTIVATE_SELF',

  // System
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
